import React from 'react';

export default function Home() {
  return (
    <div style={{ fontFamily: 'sans-serif', padding: '2rem', textAlign: 'center' }}>
      <h1>Team 26</h1>
      <p><strong>GitHub:</strong> <a href="https://github.com/DigitalCoa-ch/ai-native-team-26"> ai-native-team-26</a></p>
      <p><strong>Public URL:</strong> <a href="https://team-26.apps.digitalcoa.ch">team-26.apps.digitalcoa.ch</a></p>
      <hr />
      <h2>AI Native Enterprise Week</h2>
      <p>Building AI Native Companies in progress</p>
      <div style={{ marginTop: '2rem', color: '#666' }}>
        <p>This is a temporary homepage generated by the Lab Director.</p>
        <p>OpenClaw is ready to help you build your enterprise app.</p>
      </div>
    </div>
  );
}